name: Deploy

on:
  push:
    branches: main
  pull_request:
    branches: main
  schedule:
    - cron: "0 0 * * *"  # Runs every day at 00:00 UTC

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0  # Needed to fully update submodules

      - name: Update submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "hexium"
          entrypoint: "https://deno.land/std@0.217.0/http/file_server.ts"
          root: "build"
